export const SET_LANG = 'SET_LANG';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';

// ARTICLE DETAIL
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAILED = 'GET_ARTICLE_DETAIL_FAILED';
export const GET_ARTICLE_DETAIL_CLEAR = 'GET_ARTICLE_DETAIL_CLEAR';

// ARTICLE LIST
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';
export const GET_ARTICLES_CLEAR = 'GET_ARTICLES_CLEAR';

// ARTICLE CATEGORY
export const GET_ARTICLE_CATEGORIES = 'GET_ARTICLE_CATEGORIES';
export const GET_ARTICLE_CATEGORIES_SUCCESS = 'GET_ARTICLE_CATEGORIES_SUCCESS';
export const GET_ARTICLE_CATEGORIES_FAILED = 'GET_ARTICLE_CATEGORIES_FAILED';
export const GET_ARTICLE_CATEGORIES_CLEAR = 'GET_ARTICLE_CATEGORIES_CLEAR';
