export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCT_CLEAR = 'GET_PRODUCT_CLEAR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCTS_CLEAR = 'GET_PRODUCTS_CLEAR';

export const GET_LIST_RS = 'GET_LIST_RS';
export const GET_LIST_RS_SUCCESS = 'GET_LIST_RS_SUCCESS';
export const GET_LIST_RS_FAILED = 'GET_LIST_RS_FAILED';
export const GET_LIST_RS_CLEAR = 'GET_LIST_RS_CLEAR';

export const GET_PERSONAL_RIPLAY = 'GET_PERSONAL_RIPLAY';
export const GET_PERSONAL_RIPLAY_SUCCESS = 'GET_PERSONAL_RIPLAY_SUCCESS';
export const GET_PERSONAL_RIPLAY_FAILED = 'GET_PERSONAL_RIPLAY_FAILED';
export const GET_PERSONAL_RIPLAY_CLEAR = 'GET_PERSONAL_RIPLAY_CLEAR';

export const SET_SUBMISSION = 'SET_SUBMISSION';
export const SET_SUBMISSION_SUCCESS = 'SET_SUBMISSION_SUCCESS';
export const SET_SUBMISSION_FAILED = 'SET_SUBMISSION_FAILED';
export const SET_SUBMISSION_CLEAR = 'SET_SUBMISSION_CLEAR';

export const GET_CURRENT_SUBS = 'GET_CURRENT_SUBS';
export const GET_CURRENT_SUBS_SUCCESS = 'GET_CURRENT_SUBS_SUCCESS';
export const GET_CURRENT_SUBS_FAILED = 'GET_CURRENT_SUBS_FAILED';
export const GET_CURRENT_SUBS_CLEAR = 'GET_CURRENT_SUBS_CLEAR';

export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN_FAILED = 'GET_CAMPAIGN_FAILED';
export const GET_CAMPAIGN_CLEAR = 'GET_CAMPAIGN_CLEAR';

export const GET_POLICY_DETAIL = 'GET_POLICY_DETAIL';
export const GET_POLICY_DETAIL_SUCCESS = 'GET_POLICY_DETAIL_SUCCESS';
export const GET_POLICY_DETAIL_FAILED = 'GET_POLICY_DETAIL_FAILED';
export const GET_POLICY_DETAIL_CLEAR = 'GET_POLICY_DETAIL_CLEAR';

export const GET_ELIGIBLE_SUBMISSION = 'GET_ELIGIBLE_SUBMISSION';
export const GET_ELIGIBLE_SUBMISSION_SUCCESS =
  'GET_ELIGIBLE_SUBMISSION_SUCCESS';
export const GET_ELIGIBLE_SUBMISSION_FAILED = 'GET_ELIGIBLE_SUBMISSION_FAILED';
export const GET_ELIGIBLE_SUBMISSION_CLEAR = 'GET_ELIGIBLE_SUBMISSION_CLEAR';

export const GET_IS_USER_ELIGIBLE = 'GET_IS_USER_ELIGIBLE';
export const GET_IS_USER_ELIGIBLE_SUCCESS = 'GET_IS_USER_ELIGIBLE_SUCCESS';
export const GET_IS_USER_ELIGIBLE_FAILED = 'GET_IS_USER_ELIGIBLE_FAILED';
export const GET_IS_USER_ELIGIBLE_CLEAR = 'GET_IS_USER_ELIGIBLE_CLEAR';

export const SET_IS_AGREEMENT_VISIBLE = 'SET_IS_AGREEMENT_VISIBLE';
export const SET_INVITEE_USER_ID = 'SET_INVITEE_USER_ID';
export const SET_PLAN_CODE = 'SET_PLAN_CODE';

export const SET_WAITING = 'SET_WAITING';
export const SET_WAITING_SUCCESS = 'SET_WAITING_SUCCESS';
export const SET_WAITING_FAILED = 'SET_WAITING_FAILED';
export const SET_WAITING_CLEAR = 'SET_WAITING_CLEAR';

export const SET_PERSON_ELIGIBLE = 'SET_PERSON_ELIGIBLE';
export const SET_PERSON_ELIGIBLE_SUCCESS = 'SET_PERSON_ELIGIBLE_SUCCESS';
export const SET_PERSON_ELIGIBLE_FAILED = 'SET_PERSON_ELIGIBLE_FAILED';
export const SET_PERSON_ELIGIBLE_CLEAR = 'SET_PERSON_ELIGIBLE_CLEAR';

export const GET_ELIGIBLE_POS = 'GET_ELIGIBLE_POS';
export const GET_ELIGIBLE_POS_SUCCESS = 'GET_ELIGIBLE_POS_SUCCESS';
export const GET_ELIGIBLE_POS_FAILED = 'GET_ELIGIBLE_POS_FAILED';
export const GET_ELIGIBLE_POS_CLEAR = 'GET_ELIGIBLE_POS_CLEAR';

export const GET_TOTAL_CLAIM = 'GET_TOTAL_CLAIM';
export const GET_TOTAL_CLAIM_SUCCESS = 'GET_TOTAL_CLAIM_SUCCESS';
export const GET_TOTAL_CLAIM_FAILED = 'GET_TOTAL_CLAIM_FAILED';
export const GET_TOTAL_CLAIM_CLEAR = 'GET_TOTAL_CLAIM_CLEAR';
