export { default as RegisterOtp } from './RegisterOtp';
export { default as RegisterMain } from './RegisterMain';
export { default as RegisterPolis } from './RegisterPolis';
export { default as RegisterInput } from './RegisterInput';
export { default as RegisterNextStep } from './RegisterNextStep';
export { default as RegisterPolisOtp } from './RegisterPolisOtp';
export { default as RegisterSertifikat } from './RegisterSertifikat';
export { default as RegisterPin } from './RegisterPin';
export { default as RegisterTerms } from './RegisterTerms';
