export const GET_RESET_PASSWORD = 'GET_RESET_PASSWORD';
export const GET_RESET_PASSWORD_SUCCESS = 'GET_RESET_PASSWORD_SUCCESS';
export const GET_RESET_PASSWORD_FAILED = 'GET_RESET_PASSWORD_FAILED';
export const GET_RESET_PASSWORD_CLEAR = 'GET_RESET_PASSWORD_CLEAR';

export const SET_RESET_PASSWORD = 'SET_RESET_PASSWORD';
export const SET_RESET_PASSWORD_SUCCESS = 'SET_RESET_PASSWORD_SUCCESS';
export const SET_RESET_PASSWORD_FAILED = 'SET_RESET_PASSWORD_FAILED';
export const SET_RESET_PASSWORD_CLEAR = 'SET_RESET_PASSWORD_CLEAR';
