export const GET_CHECKALREADY_INVITE = 'GET_CHECKALREADY_INVITE';
export const GET_CHECKALREADY_INVITE_SUCCESS =
  'GET_CHECKALREADY_INVITE_SUCCESS';
export const GET_CHECKALREADY_INVITE_FAILED = 'GET_CHECKALREADY_INVITE_FAILED';
export const GET_CHECKALREADY_INVITE_CLEAR = 'GET_CHECKALREADY_INVITE_CLEAR';

export const GET_CHECKALREADY_SUBSCRIBE = 'GET_CHECKALREADY_SUBSCRIBE';
export const GET_CHECKALREADY_SUBSCRIBE_SUCCESS =
  'GET_CHECKALREADY_SUBSCRIBE_SUCCESS';
export const GET_CHECKALREADY_SUBSCRIBE_FAILED =
  'GET_CHECKALREADY_SUBSCRIBE_FAILED';
export const GET_CHECKALREADY_SUBSCRIBE_CLEAR =
  'GET_CHECKALREADY_SUBSCRIBE_CLEAR';

export const GET_ADDLINK = 'GET_ADDLINK';
export const GET_ADDLINK_SUCCESS = 'GET_ADDLINK_SUCCESS';
export const GET_ADDLINK_FAILED = 'GET_ADDLINK_FAILED';
export const GET_ADDLINK_CLEAR = 'GET_ADDLINK_CLEAR';

export const GET_INVITATION_LINK = 'GET_INVITATION_LINK';
export const GET_INVITATION_LINK_SUCCESS = 'GET_INVITATION_LINK_SUCCESS';
export const GET_INVITATION_LINK_FAILED = 'GET_INVITATION_LINK_FAILED';
export const GET_INVITATION_LINK_CLEAR = 'GET_INVITATION_LINK_CLEAR';

export const GET_INVITATION_LIST_FRIEND = 'GET_INVITATION_LIST_FRIEND';
export const GET_INVITATION_LIST_FRIEND_SUCCESS =
  'GET_INVITATION_LIST_FRIEND_SUCCESS';
export const GET_INVITATION_LIST_FRIEND_FAILED =
  'GET_INVITATION_LIST_FRIEND_FAILED';
export const GET_INVITATION_LIST_FRIEND_CLEAR =
  'GET_INVITATION_LIST_FRIEND_CLEAR';

export const GET_CHECK_STATUS_REGISTER = 'GET_CHECK_STATUS_REGISTER';
export const GET_CHECK_STATUS_REGISTER_SUCCESS =
  'GET_CHECK_STATUS_REGISTER_SUCCESS';
export const GET_CHECK_STATUS_REGISTER_FAILED =
  'GET_CHECK_STATUS_REGISTER_FAILED';
export const GET_CHECK_STATUS_REGISTER_CLEAR =
  'GET_CHECK_STATUS_REGISTER_CLEAR';

export const GET_PENDING_INVITES = 'GET_PENDING_INVITES';
export const GET_PENDING_INVITES_SUCCESS = 'GET_PENDING_INVITES_SUCCESS';
export const GET_PENDING_INVITES_FAILED = 'GET_PENDING_INVITES_FAILED';
export const GET_PENDING_INVITES_CLEAR = 'GET_PENDING_INVITES_CLEAR';

export const GET_CHECK_INVITEE = 'GET_CHECK_INVITEE';
export const GET_CHECK_INVITEE_SUCCESS = 'GET_CHECK_INVITEE_SUCCESS';
export const GET_CHECK_INVITEE_FAILED = 'GET_CHECK_INVITEE_FAILED';
export const GET_CHECK_INVITEE_CLEAR = 'GET_CHECK_INVITEE_CLEAR';

export const GET_CHECK_MAX_INVITE = 'GET_CHECK_MAX_INVITE';
export const GET_CHECK_MAX_INVITE_SUCCESS = 'GET_CHECK_MAX_INVITE_SUCCESS';
export const GET_CHECK_MAX_INVITE_FAILED = 'GET_CHECK_MAX_INVITE_FAILED';
export const GET_CHECK_MAX_INVITE_CLEAR = 'GET_CHECK_MAX_INVITE_CLEAR';
