export const GET_POLICY_SUMMARY = 'GET_POLICY_SUMMARY';
export const GET_POLICY_SUMMARY_SUCCESS = 'GET_POLICY_SUMMARY_SUCCESS';
export const GET_POLICY_SUMMARY_FAILED = 'GET_POLICY_SUMMARY_FAILED';
export const GET_POLICY_SUMMARY_CLEAR = 'GET_POLICY_SUMMARY_CLEAR';

export const GET_POLICY_SELF_DATA = 'GET_POLICY_SELF_DATA';
export const GET_POLICY_SELF_DATA_SUCCESS = 'GET_POLICY_SELF_DATA_SUCCESS';
export const GET_POLICY_SELF_DATA_FAILED = 'GET_POLICY_SELF_DATA_FAILED';
export const GET_POLICY_SELF_DATA_CLEAR = 'GET_POLICY_SELF_DATA_CLEAR';

export const GET_POLICY_BENEFIT = 'GET_POLICY_BENEFIT';
export const GET_POLICY_BENEFIT_SUCCESS = 'GET_POLICY_BENEFIT_SUCCESS';
export const GET_POLICY_BENEFIT_FAILED = 'GET_POLICY_BENEFIT_FAILED';
export const GET_POLICY_BENEFIT_CLEAR = 'GET_POLICY_BENEFIT_CLEAR';

export const GET_POLICY_FUNDS = 'GET_POLICY_FUNDS';
export const GET_POLICY_FUNDS_SUCCESS = 'GET_POLICY_FUNDS_SUCCESS';
export const GET_POLICY_FUNDS_FAILED = 'GET_POLICY_FUNDS_FAILED';
export const GET_POLICY_FUNDS_CLEAR = 'GET_POLICY_FUNDS_CLEAR';

export const GET_POLICY_CLAIM = 'GET_POLICY_CLAIM';
export const GET_POLICY_CLAIM_SUCCESS = 'GET_POLICY_CLAIM_SUCCESS';
export const GET_POLICY_CLAIM_FAILED = 'GET_POLICY_CLAIM_FAILED';
export const GET_POLICY_CLAIM_CLEAR = 'GET_POLICY_CLAIM_CLEAR';

export const GET_POLICY_CLAIM_DETAIL = 'GET_POLICY_CLAIM_DETAIL';
export const GET_POLICY_CLAIM_DETAIL_SUCCESS =
  'GET_POLICY_CLAIM_DETAIL_SUCCESS';
export const GET_POLICY_CLAIM_DETAIL_FAILED = 'GET_POLICY_CLAIM_DETAIL_FAILED';
export const GET_POLICY_CLAIM_DETAIL_CLEAR = 'GET_POLICY_CLAIM_DETAIL_CLEAR';

export const GET_POLICY_DOWNLOAD = 'GET_POLICY_DOWNLOAD';
export const GET_POLICY_DOWNLOAD_SUCCESS = 'GET_POLICY_DOWNLOAD_SUCCESS';
export const GET_POLICY_DOWNLOAD_FAILED = 'GET_POLICY_DOWNLOAD_FAILED';
export const GET_POLICY_DOWNLOAD_CLEAR = 'GET_POLICY_DOWNLOAD_CLEAR';
