export const authInitialState = {
  lang: 'id',
  colorScheme: 'light',
  userData: {
    userId: '',
    deviceId: '',
    email: '',
    name: '',
    mobilePhoneNumber: '',
    thumbnailPhotoKey: '',
    alreadyKYC: false,
    userParty: null,
    alreadyLivenessTest: false,
    alreadySetPin: false,
    kkpmFlag: [],
    ekycId: '',
    alreadySetMPin: false,
    isReKYC: false,
    isReLivenessTest: false,
    isReUploadIdCard: false,
    isReLivenessTestAndReUploadIdCard: false,
    alreadyReLivenessTest: false,
    eventCode: '',
    refferalCode: '',
  },
  widgetToggle: {
    widgetInvitation: true,
  },
  token: {
    refresh_token: '',
    token_type: 'bearer',
    access_token: '',
    expires_in: 0,
    error_description: null,
    error: null,
  },
};
