export const SET_LANG = 'SET_LANG';
export const SET_AUTH = 'SET_AUTH';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_WIDGET_TOGGLE = 'SET_WIDGET_TOGGLE';

export const SET_CLEAR_AUTH = 'SET_CLEAR_AUTH';
export const SET_CLEAR_AUTH_SUCCESS = 'SET_CLEAR_AUTH_SUCCESS';
export const SET_CLEAR_AUTH_FAILED = 'SET_CLEAR_AUTH_FAILED';

export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';
export const SET_LOGOUT_FAILED = 'SET_LOGOUT_FAILED';
export const SET_LOGOUT_CLEAR = 'SET_LOGOUT_CLEAR';

export const SET_CLEAR_REFRESH_TOKEN = 'SET_CLEAR_REFRESH_TOKEN';

export const GET_CHECK_ISSUED_POLICY = 'GET_CHECK_ISSUED_POLICY';
export const GET_CHECK_ISSUED_POLICY_SUCCESS =
  'GET_CHECK_ISSUED_POLICY_SUCCESS';
export const GET_CHECK_ISSUED_POLICY_FAILED = 'GET_CHECK_ISSUED_POLICY_FAILED';
