export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_REQUEST_LOCATION_PERMISSION =
  'SET_REQUEST_LOCATION_PERMISSION';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_IS_SHOW_MODAL_COMING_SOON = 'SET_IS_SHOW_MODAL_COMING_SOON';
export const SET_IS_SHOW_MODAL_CUSTOMER_CARE =
  'SET_IS_SHOW_MODAL_CUSTOMER_CARE';
export const SET_LOADING = 'SET_LOADING';
export const SET_UPLOAD_IMAGE_PROGRESS = 'SET_UPLOAD_IMAGE_PROGRESS';
export const SET_TOASTMSG = 'SET_TOASTMSG';
export const SET_IS_SHOW_MODAL_INTERNAL_SERVER_ERROR =
  'SET_IS_SHOW_MODAL_INTERNAL_SERVER_ERROR';
export const SET_IS_SHOW_MODAL_BAD_REQUEST = 'SET_IS_SHOW_MODAL_BAD_REQUEST';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_IS_COMING_FROM_SCREEN = 'SET_IS_COMING_FROM_SCREEN';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_IS_COMING_FROM_DEEPLINK = 'SET_IS_COMING_FROM_DEEPLINK';
export const SET_IS_SHOW_FAILED_MODAL_LOGIN = 'SET_IS_SHOW_FAILED_MODAL_LOGIN';
export const SET_ISPROGRESS_CODEPUSH = 'SET_ISPROGRESS_CODEPUSH';
export const SET_STATUS_CODEPUSH = 'SET_STATUS_CODEPUSH';
export const SET_IS_ALREADY_LAUNCHED = 'SET_IS_ALREADY_LAUNCHED';
export const SET_IS_COMING_FROM_DEEPLINK_URL =
  'SET_IS_COMING_FROM_DEEPLINK_URL';
